import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Sales Lead",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    > 
    <Toaster position="top-right" />
      <body className="min-h-full flex flex-col">
          {children}
        </body>
    </html>
  );
}
